apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuberity-server
rules:
  - apiGroups:
      - ''
      - apps
    resources:
      - deployments
      - services
      - pods
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
