apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuberity-api-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuberity-server
subjects:
  - kind: ServiceAccount
    name: kuberity-controller
    namespace: kuberity
